### ISSUE TITLE
Warn about running `thelounge` under wrong user

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge-deb#32]
Right now it crashes with permission denied when trying to read the user.

Perhaps the it should automatically `sudo thelounge`?

**Comment by astorije** [comment]
You mean if I need to create a user and run `thelounge add foo` with my regular user (i.e. not `thelounge` user), it will create a user config with incorrect owner?

> Perhaps the it should automatically sudo thelounge?

What do you mean? When creating a user?

I can't think of another tool that would do something similar, are there any existing patterns we could leverage?
I feel like for that kind of things, there is usually a `thingd` and a `thingctl`, `thingd` being able to write with the correct privileges, and `thingctl` just delegating commands to `thingd`.

**Comment by xPaw** [comment]
> You mean if I need to create a user and run thelounge add foo with my regular user (i.e. not thelounge user), it will create a user config with incorrect owner?

**Comment by astorije** [comment]
I don't know if it's wise to run with `sudo` though.
Correct me if I'm wrong, does it require user `thelounge` to have sudo privileges? That could do a lot of damage if something goes wrong, no?

**Comment by xPaw** [comment]
> does it require user thelounge to have sudo privileges? 

The other way around. If you run `thelounge` CLI as root, it should execute the node binary as `thelounge` user to avoid permission problems.

**Comment by astorije** [comment]
That makes sense. As long as we don't ship a way to go root or some sort of privileged user, I'm cool with it!

**Comment by xPaw** [comment]
Lounge itself does this now.
