### ISSUE TITLE
Build ARM package (for raspberry)

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge-deb#36]
Might need to use docker or something for this?

**Comment by MartijnBraam** [comment]
This package doesn't contain any architecture dependent code and the arch is already set to all, it should Just Work(tm) on armhf/arm64 without changes.

**Comment by xPaw** [comment]
A separate package is needed due to `sqlite3` dependency, which needs to be manually compiled on arm64 (mapbox doesn't provide precompiled bins).

It's installed here: https://github.com/thelounge/thelounge-deb/blob/4af1a83d4f49a586477dfa010be17ed97e01d5bd/debian/postinst#L6

I suspect it would work if we added `build-essential` to required dependencies, but the compilation would still take a long time since raspberry is a low power device.

**Comment by xPaw** [comment]
I believe we should at least add `build-essential [arm64 armel armhf]` to `Depends` in the control file.

**Comment by vandot** [comment]
@xPaw you have a great implementation in [zeromq.js](https://github.com/zeromq/zeromq.js)
Using [prebuild](https://github.com/prebuild/prebuild), custom [cross_compile.sh](https://github.com/zeromq/zeromq.js/blob/master/scripts/cross_compile.sh) and [travis](https://github.com/zeromq/zeromq.js/blob/master/.travis.yml)

**Comment by xPaw** [comment]
I've had a couple of guys try installing .deb on raspberry, and looks like it works out of the box! (sqlite gets compiled on its own).
