### ISSUE TITLE
Can't Install v3.0.0-rc.5

### ISSUE THREAD

**Issue by xnaas** [thelounge/thelounge-deb#46]
Wanted to install RC5, but no dice.

![img1](https://xnaas.info/img/IntelligentHardGypsymoth.png)

![img2](https://xnaas.info/img/BareImpracticalFlee.png)

Not sure exactly what I'm doing wrong or missing, but I'm sure it's something simple/stupid. 🙃

**Comment by Duckle29** [comment]
Update node
https://nodejs.org/en/download/package-manager/

**Comment by xnaas** [comment]
Bah, should've known better than to rely on the version included in the 18.04 LTS release. Thanks. Will upgrade and close.

**Comment by xnaas** [comment]
Node v11 to the rescue. Thank you @Duckle29. 👏 👍 🎉 🎊

**Comment by Duckle29** [comment]
No problem. Dealt with that issue twice today. Pushing node to friends :P
