### ISSUE TITLE
Replaces

### ISSUE THREAD

**Issue by d7415** [thelounge/thelounge-deb#48]
Trying to install v3.0.0-rc.6, there are conflicts with 2.7.1 due to the package name change. I think this warrants a `Replaces` line. Possibly [more](https://wiki.debian.org/RenamingPackages).

**Comment by d7415** [comment]
`Replaces: lounge (<< 3.0.0)` allows installation. Some more elegant solution (removing/moving old files and user/group) might be good though.

**Comment by astorije** [comment]
Interesting idea. @d7415 do you want to help with that?
@xPaw, what do you think?

**Comment by xPaw** [comment]
Sounds alright

**Comment by xPaw** [comment]
@d7415 make a pr?

**Comment by d7415** [comment]
I'll see what I can do...
