### ISSUE TITLE
`sed: no input files` when running the build script

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge-deb#6]
When running `./build-package`, this is among the output:

```sh
sed: no input files
```

This is from [that line](https://github.com/thelounge/deb-lounge/blob/a9c4cb95574977b42c63ca8d0fd1b5a6d4881068/build-package#L31).

I'm not sure if this hides anything though, I haven't looked.

**Comment by xPaw** [comment]
Since we publish builds from Travis now, we could just remove that grep/sed line.

**Comment by astorije** [comment]
I'm forgetting, what does this line do already? And how does publishing in Travis affect it?

**Comment by xPaw** [comment]
I believe the idea was to hide the full path where you have the build script (on your machine). As we build on Travis, it's gonna be `/home/travis/build/thelounge/`.

**Comment by astorije** [comment]
Hide from the terminal output?

@maxpoulin64, do you remember why you added that line?

**Comment by xPaw** [comment]
In the final debian package, I would assume.

Honestly, just throw that line out.

**Comment by maxpoulin64** [comment]
Yeah it can be removed. Its purpose was to strip the build path from the package, so users don't see how you built it. It came from the Arch package where it throws warnings if there are references to files outside of the package itself.
