### ISSUE TITLE
Add artifact uploading to the github action (replace travis entirely)

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge-deb#62]
We have a workflow to build and test it already, just need to figure out how to attach the built .deb package to releases.

https://github.com/thelounge/thelounge-deb/blob/master/.travis.yml#L27

**Comment by xPaw** [comment]
@klausenbusk Would you be willing to try and implement this? Build/test is trivial, uploading the built dpkg file to both repos is the only tricky part here.

**Comment by klausenbusk** [comment]
> @klausenbusk Would you be willing to try and implement this?

I'm willing to take a look :)

> Build/test is trivial, uploading the built dpkg file to both repos is the only tricky part here.

Both repos? Which repos? I assume you want a action which add the deb file when a release is created?

**Comment by xPaw** [comment]
This repo and the main the lounge repo is what I meant.

**Comment by klausenbusk** [comment]
I see. I'm not sure that can be done without PAT token. Would it make sense 
to provide a APT repository? (I think we can (ab)use GitHub release for that)

**Comment by xPaw** [comment]
> Would it make sense to provide a APT repository?

It's already annoying to just maintaing this deb as-is, unsure if apt would be any easier.

> I'm not sure that can be done without PAT token.

Well that's how travis uploading works now, by having a github token.

**Comment by xPaw** [comment]
Travis is getting more hostile, and looks like the "free" plan was reset for us, which is why the builds stopped worked.

We really should migrate to github actions for building this repo. We already use it for building, the only real remaining problem is uploading the artifact.

It is possible to do, here's an example of how I did it in another repo: https://github.com/SteamDatabase/ValveResourceFormat/commit/2ebca3e6cb7fef073ea03584c62a445545932a7e#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721

e.g. see https://github.com/curl/curl/issues/7150
