### ISSUE TITLE
apt repository

### ISSUE THREAD

**Issue by azlux** [thelounge/thelounge-deb#63]
Hi,
I've setup my personal apt repository for some projects. It's great when speaking about upgrades.
I've setup an auto-update for thelounge (stable) releases based on github.

You can see it at : http://packages.azlux.fr/

I think it's can be really helpful for all users to have an apt repository.
I offer you the use of mine. If you can to use you're own, I can also help you to setup one.

Best regards,
Azlux

**Comment by xPaw** [comment]
Mostly a duplicate of #55

**Comment by azlux** [comment]
Ops, srry, I haven't see this issue.
