### ISSUE TITLE
Update thelounge.service to ensure DNS is ready at boot

### ISSUE THREAD

**Issue by bobmorane06** [thelounge/thelounge-deb#65]
I had to manually add the line in bold to `/usr/lib/systemd/system/thelounge.service` to allow thelounge to connect automatically after boot, otherwise I got a DNS unresolved error and had to manually `/connect`

[Unit]
Description=The Lounge (IRC client)
After=network.target
**After=network-online.target**

**Comment by xPaw** [comment]
Looking at https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

They suggest this:
```
After=network-online.target
Wants=network-online.target
```

Can you open a pull request?
