### ISSUE TITLE
libera.chat banned my IP

### ISSUE THREAD

**Issue by scumola** [thelounge/thelounge-deb#84]
libera.chat banned my IP since I was allowing basically an open relay to their IRC server.  I'd like to make it public like the demo site, but if this isn't possible, then I'd like a "register" option for the private mode.

Either provide a way to make the site public and not get my server IP banned, or make a register option?

`You are banned from this server- Your host is an open proxy (HTTP POST (80)) Email [bans@libera.chat](mailto:bans@libera.chat) when corrected. (2023/8/29 17.55) (banned_from_network)`

Also, the docs don't really say how to add users/passwords in /etc/thelounge/users/

**Comment by brunnre8** [comment]
this is an issue tracker and not a support forum, head to our IRC chan... with our demo instance if you can't join directly anymore.
